import { Header } from "@/components/landing/Header";
import { Footer } from "@/components/landing/Footer";
import { FullLegalDisclaimer } from "@/components/shared/LiabilityDisclaimer";
import { Shield, FileText, Scale, AlertTriangle } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <div className="mb-12">
            <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
            <p className="text-muted-foreground">
              Last updated: January 2026
            </p>
          </div>

          <FullLegalDisclaimer />

          <div className="mt-12 space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <FileText className="h-6 w-6 text-primary" />
                1. Service Description
              </h2>
              <div className="prose prose-sm text-muted-foreground">
                <p>
                  BuildQuote UK ("the Service", "we", "us") provides construction estimation, 
                  automated CAD generation, compliance checking, and project management software 
                  tools for the UK building industry.
                </p>
                <p className="mt-4">
                  The Service is intended as a planning and estimation aid only. It does not 
                  replace the need for professional architectural, structural engineering, 
                  quantity surveying, or other specialist advice.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <AlertTriangle className="h-6 w-6 text-warning" />
                2. Important Disclaimers
              </h2>
              <div className="bg-warning/5 border border-warning/20 rounded-lg p-6 space-y-4">
                <div>
                  <h3 className="font-semibold text-foreground">2.1 No Professional Certification</h3>
                  <p className="text-sm text-muted-foreground mt-2">
                    BuildQuote and its operators do not hold themselves out as chartered architects, 
                    structural engineers, quantity surveyors, solicitors, or any other regulated profession. 
                    The outputs generated by the Service are produced by automated systems and have not 
                    been reviewed or approved by qualified professionals unless explicitly stated.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-foreground">2.2 CAD Drawings</h3>
                  <p className="text-sm text-muted-foreground mt-2">
                    Automated CAD drawings are generated for indicative purposes only. They do NOT 
                    constitute certified architectural or engineering drawings. All drawings must be 
                    reviewed, verified, and signed off by a qualified architect and/or structural 
                    engineer before submission to Building Control or use for construction.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-foreground">2.3 Cost Estimates</h3>
                  <p className="text-sm text-muted-foreground mt-2">
                    All cost estimates are indicative projections based on aggregated industry data. 
                    Actual costs will vary based on site conditions, material availability, regional 
                    factors, contractor pricing, and market conditions. Estimates should not be relied 
                    upon as fixed-price quotations.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-foreground">2.4 Structural Calculations</h3>
                  <p className="text-sm text-muted-foreground mt-2">
                    Beam sizes, load calculations, foundation specifications, and all structural 
                    outputs are preliminary estimates only. A qualified structural engineer MUST 
                    perform independent calculations and provide certified structural drawings 
                    before any construction work commences.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-foreground">2.5 Compliance Checks</h3>
                  <p className="text-sm text-muted-foreground mt-2">
                    Building Regulations compliance checks are based on our interpretation of UK 
                    regulations as of January 2026. Regulations change frequently. Approval from 
                    our automated systems does NOT constitute Building Control approval. Users must 
                    verify current requirements with their local authority.
                  </p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <Scale className="h-6 w-6 text-primary" />
                3. Limitation of Liability
              </h2>
              <div className="prose prose-sm text-muted-foreground">
                <p>
                  <strong>3.1</strong> To the fullest extent permitted by law, BuildQuote Limited, 
                  its directors, employees, agents, and affiliates shall not be liable for any 
                  direct, indirect, incidental, consequential, special, or exemplary damages arising 
                  from:
                </p>
                <ul className="mt-4 space-y-2">
                  <li>Use or inability to use the Service</li>
                  <li>Reliance on any outputs, estimates, or calculations provided</li>
                  <li>Construction defects or failures</li>
                  <li>Regulatory non-compliance or enforcement action</li>
                  <li>Cost overruns or budget variances</li>
                  <li>Project delays or schedule impacts</li>
                  <li>Personal injury or property damage</li>
                  <li>Loss of profits, revenue, or business opportunity</li>
                </ul>
                
                <p className="mt-4">
                  <strong>3.2</strong> In no event shall our total liability exceed the amount 
                  paid by you for the Service in the 12 months preceding the claim.
                </p>
                
                <p className="mt-4">
                  <strong>3.3</strong> Some jurisdictions do not allow the exclusion of certain 
                  warranties or limitation of liability. In such jurisdictions, our liability 
                  shall be limited to the maximum extent permitted by law.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <Shield className="h-6 w-6 text-primary" />
                4. User Responsibilities
              </h2>
              <div className="prose prose-sm text-muted-foreground">
                <p>By using the Service, you agree to:</p>
                <ul className="mt-4 space-y-2">
                  <li>
                    <strong>Independent Verification:</strong> Obtain independent professional 
                    verification of all outputs before reliance, submission to authorities, 
                    or commencement of construction.
                  </li>
                  <li>
                    <strong>Professional Oversight:</strong> Engage appropriately qualified 
                    professionals (architects, structural engineers, quantity surveyors) for 
                    your project as required by law and good practice.
                  </li>
                  <li>
                    <strong>Accuracy of Inputs:</strong> Provide accurate and complete information 
                    when using the Service. Outputs are only as reliable as the inputs provided.
                  </li>
                  <li>
                    <strong>Compliance:</strong> Ensure all work complies with applicable Building 
                    Regulations, planning permissions, and other legal requirements regardless of 
                    any outputs from the Service.
                  </li>
                  <li>
                    <strong>Indemnification:</strong> Indemnify and hold harmless BuildQuote from 
                    any claims arising from your use of the Service or reliance on its outputs.
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
              <div className="prose prose-sm text-muted-foreground">
                <p>
                  All content, software, algorithms, and data within the Service remain the 
                  property of BuildQuote Limited. Users are granted a limited, non-exclusive 
                  license to use outputs for their own projects. Outputs may not be resold or 
                  redistributed commercially without prior written consent.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Governing Law</h2>
              <div className="prose prose-sm text-muted-foreground">
                <p>
                  These terms are governed by and construed in accordance with the laws of 
                  England and Wales. Any disputes shall be subject to the exclusive jurisdiction 
                  of the courts of England and Wales.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. Contact</h2>
              <div className="prose prose-sm text-muted-foreground">
                <p>
                  For questions about these terms, please contact:
                </p>
                <p className="mt-2">
                  <strong>BuildQuote Limited</strong><br />
                  Email: legal@buildquote.co.uk<br />
                  Registered in England & Wales
                </p>
              </div>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
